### ISSUE TITLE
model gives issue when more contents are added

### ISSUE THREAD

**Issue by santoshyadav198613** [ngx-builders/ngx-bulma#280]
**Describe the bug**

**To Reproduce**
1. Go to 'model'
2. Click on 'open model'

**Expected behavior**
1. Should have close icon, based on configuration
2. content should be inside model with scrollbar
3. footer should be visible.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by AnkitSharma-007** [comment]
Error screenshot :- 

![image](https://user-images.githubusercontent.com/33789321/80277878-b4744780-870f-11ea-8812-1b9c63e9a581.png)
