### ISSUE TITLE
Possiblity of providing an data table with Bulma css support

### ISSUE THREAD

**Issue by santoshyadavdev** [ngx-builders/ngx-bulma#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A data table with Bulma css which renders the column and rows.
**Describe alternatives you've considered**

**Additional context**

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by git-srinivas** [comment]
Yes. I am working on it santosh.
