### ISSUE TITLE
Move the logic into navbar component

### ISSUE THREAD

**Issue by santoshyadavdev** [ngx-builders/ngx-bulma#437]
**Describe the bug**

**Expected behavior**

Currently, we have written the logic to close the hamburger menu in the app
https://github.com/ngx-builders/ngx-bulma/blob/main/projects/bulma-app/src/app/navbar/doc-navbar/doc-navbar.component.html#L24

The logic should nor be exposed to end-user and should be part of the library.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by shanmukhateja** [comment]
Hi @santoshyadavdev ,

I am interested in solving this issue and willing to submit a PR. Do you have a plan of approach?

The main issue I currently see is gaining access to `ElementRef` without user explicitly declaring it in HTML? In case of `/projects/bulma-app/src/app/navbar/navbar.component.html`, there are multiple instances of `bu-nav-brand` for each color variant.
We could, in theory, inject `ElementRef` in `bu-nav-brand`constructor and use `querySelector` but I personally don't like this approach.

**Comment by santoshyadavdev** [comment]
We would love to have the PR. let me know if you need any help 🤗

**Comment by shanmukhateja** [comment]
Hi @santoshyadavdev 

How do we gain access to `ElementRef` when there are multiple instances of `bu-nav-brand` like in the case of `/projects/bulma-app/src/app/navbar/navbar.component.html`?

**Comment by santoshyadavdev** [comment]
> Hi @santoshyadavdev
> 
> How do we gain access to `ElementRef` when there are multiple instances of `bu-nav-brand` like in the case of `/projects/bulma-app/src/app/navbar/navbar.component.html`?

You can use ViewChildren to get access.

**Comment by shanmukhateja** [comment]
Hi @santoshyadavdev ,

I am currently working on this issue on my fork at:

https://github.com/shanmukhateja/ngx-bulma/tree/refactor-menu-close

Current progress: Navbar menu clicks work either  on web app's main Navbar header OR navbar component demo code in documentation. 

Could you please look into my code and help me with it? I will provide a PR with accordance to your CONTRIBUTING.md requirements once the code is working and so it will be replaced in the future.

I just need a review from your end to check if my approach to solving the issue is correct.

**Comment by santoshyadavdev** [comment]
Sure let me check, and thank you 😊

**Comment by shanmukhateja** [comment]
Hi @santoshyadavdev,

I updated the PR and my commit message has been updated accordingly.

**Comment by santoshyadavdev** [comment]
closed by https://github.com/ngx-builders/ngx-bulma/pull/453

**Comment by shanmukhateja** [comment]
Hey @santoshyadavdev,

You seem to have forgotten to close this issue.

**Comment by santoshyadavdev** [comment]
Oops my bad 😅
