### ISSUE TITLE
rename package to @ngx-builders/ngx-bulma

### ISSUE THREAD

**Issue by santoshyadavdev** [ngx-builders/ngx-bulma#450]
rename package to @ngx-builders/ngx-bulma

**Comment by iamsurajdc** [comment]
Hi @santoshyadavdev ,
Could you please elaborate on issue bit more ?

**Comment by santoshyadavdev** [comment]
Hey @iamsurajdc , this is already done, in PR https://github.com/ngx-builders/ngx-bulma/pull/480

**Comment by iamsurajdc** [comment]
Being said that, I think issue would be closed as an effect.
Cheers! @santoshyadavdev .
